name: No Assertions
on:
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: "Extra Resolve Options"
        required: false
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
jobs:
  ndebug:
    name: No Assertions
    uses: steinwurf/nodebug-action/.github/workflows/action.yml@8.0.0
    with:
      extra_resolve_options: ${{ github.event.inputs.extra_resolve_options }}
